server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: never
    whitelabel:
      enabled: false
spring:
  security:
    user:
      name: sa
      password: sa
      roles:
      - USER
  data:
    rest:
      base-path: /api
      default-page-size: 5
      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:invoicedb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /console
